name: Continue on error
on:
  push:
    branches:
      - master
env:
  TEST_SUCCEDED: false
jobs:
  get_code:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          if [ ${{ env.TEST_SUCCEDED }} == true ]; then
            echo "Test succeded"
          elif [ ${{ env.TEST_SUCCEDED }} == 'false' ]; then
            echo "Test failed"
          else
            echo "Invalid success/failure code"
          fi
