name: Continue on error
on:
  push:
    branches:
      - master
env:
  TEST_SUCCEDED: false
jobs:
  get_code:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        if: ${{env.TEST_SUCCEDED}} == true
        run: echo "Success message"
      - name: Print failure message
        if: ${{env.TEST_SUCCEDED}} == false
        run: echo "Failure message"
