name: CI/CD

on:
  push:
    branches: [master]
  # pull_request:
  # branches: [ main ]

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Running actions triggered by ${{github.event_name}}
        run: Running actions triggered by ${{github.event_name}}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
        # node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: echo "Running tests and generating reports ... ..."

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
        # node-version: [18.x, 20.x, 22.x, 23.x]
    needs: test
    steps:
      - name: Build the app
        run: echo "Building your app ... ..."

  containerize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
        # node-version: [18.x, 20.x, 22.x, 23.x]
    needs: build
    steps:
      - name: Build docker container
        run: echo "Building and pushing docker container"

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
        # node-version: [18.x, 20.x, 22.x, 23.x]
    needs: containerize
    steps:
      - name: Deploy the app
        run: echo "Deploying your app tow AWS or GCP or Azure... ..."
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#  |
#   git config --global user.name $user_name
#   git config --global user.email $user_email
#   git remote set-url origin https://${github_token}@github.com/${repository}
#   npm run deploy
# env:
#   user_name: 'github-actions[bot]'
#   user_email: 'github-actions[bot]@users.noreply.github.com'
#   github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#   repository: ${{ github.repository }}
# name: GitHub Actions CI/CD Example
# run-name: Testing out GitHub Actions 🚀
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#           echo ${{ job }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."
