name: Some Tests

on:
  push:
    branches: [master]

env:
  FLAG: true

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Running actions triggered by ${{github.event_name}}
        run: echo "Running actions triggered by ${{github.event_name}}"
      - name: Pring flag name
        run: echo "Variable flag is ${{env.FLAG}}"
